### ISSUE TITLE
Dependencies: Enum is now built-in module in Python

### ISSUE THREAD

**Issue by jablka** [MRNL-/LiturgicalCalendarUtils#21]
Hi @MRNL- ,
I also see that in `readme.md` you mention as dependency: Enum34 module.
But that is now built-in in Python, see https://pypi.org/project/enum34/ 
"_Python 3.4 Enum backported to 3.3, 3.2, 3.1, 2.7, 2.6, 2.5, and 2.4_" , 

also here https://docs.python.org/3/library/enum.html

**Comment by MRNL-** [comment]
Yes indeed !
I'll fix this along the other issue (port the whole project to Py3) so i'll close this one as duplicate.

Thanks !
